import Head from 'next/head'
import React, { Component }  from 'react'

export default function Layout(props) {
    return (
        <div>
            <Head>
                <title>LaslesVPN</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300&display=swap" rel="stylesheet"></link>
            </Head>
            {props.children}
        </div>
    )
}
